import { jsPDF } from "jspdf";
import { Book } from "../types";

export const pdfService = {
  generatePdf: (book: Book) => {
    // Orientation 'p' (portrait), unit 'mm', format 'a4'
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    
    // Fonts
    doc.setFont("times", "normal");

    // 1. COVER PAGE
    if (book.coverImage) {
      try {
        // Add image. Using format 'JPEG' usually works well for base64 data uris in jsPDF
        // If image is PNG, it might need 'PNG'. 
        // Simple heuristic: check mime type in data uri
        let format = "JPEG";
        if (book.coverImage.startsWith("data:image/png")) {
            format = "PNG";
        }
        
        // We want the cover to fill the page
        doc.addImage(book.coverImage, format, 0, 0, pageWidth, pageHeight);
      } catch (e) {
        console.warn("Could not add cover image to PDF", e);
      }
      doc.addPage();
    }

    // 2. TITLE PAGE
    doc.setFont("times", "bold");
    doc.setFontSize(28);
    // Align center: x = width/2, y = 1/3 down
    doc.text(book.title, pageWidth / 2, pageHeight / 3, { align: "center", maxWidth: pageWidth - 40 });
    
    doc.setFont("times", "italic");
    doc.setFontSize(16);
    doc.text(`by ${book.author}`, pageWidth / 2, (pageHeight / 3) + 20, { align: "center" });
    
    doc.setFont("times", "normal");
    doc.setFontSize(12);
    doc.text(`${book.genre} | ${book.tone}`, pageWidth / 2, pageHeight - 30, { align: "center" });
    doc.text(`Generated by Lumina AI`, pageWidth / 2, pageHeight - 20, { align: "center" });
    
    doc.addPage();

    // 3. CHAPTERS
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);
    const lineHeight = 7;
    
    book.chapters.forEach((chapter, index) => {
      // Chapter Title
      doc.setFont("times", "bold");
      doc.setFontSize(20);
      doc.text(chapter.title, pageWidth / 2, margin + 10, { align: "center" });
      
      doc.setFont("times", "normal");
      doc.setFontSize(12);

      let cursorY = margin + 30;

      // Content Processing
      // We manually split text to ensure we handle page breaks correctly
      const paragraphs = chapter.content.split('\n');
      
      paragraphs.forEach(para => {
         if (!para.trim()) {
             cursorY += lineHeight; // Extra space for paragraph breaks
             return;
         }
         
         // indent first line of paragraph
         const indent = "    ";
         const lines = doc.splitTextToSize(indent + para, maxLineWidth);
         
         lines.forEach((line: string) => {
             // Check if we need a new page
             if (cursorY > pageHeight - margin) {
                 doc.addPage();
                 cursorY = margin + 10;
             }
             
             doc.text(line, margin, cursorY, { align: "justify", maxWidth: maxLineWidth });
             cursorY += lineHeight;
         });
         
         // Space between paragraphs
         cursorY += lineHeight / 2;
      });

      // Add page break after chapter unless it's the last one
      if (index < book.chapters.length - 1) {
          doc.addPage();
      }
    });

    doc.save(`${book.title.replace(/\s+/g, '_')}.pdf`);
  }
};